# -*- coding: utf-8 -*-
"""EDA Amazon Review Analysis_WomenClothing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oe963x_H8NstSj3u2Xu1G6VmlOqkm6P6
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive/')
# %cd /gdrive

ls

cd/gdrive/MyDrive/Amazon Review/

ls

import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/gdrive/MyDrive/Amazon Review'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from matplotlib.colors import ListedColormap
import seaborn as sns
from cycler import cycler
from IPython.display import display
import datetime

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import mutual_info_classif

df=pd.read_csv("/gdrive/MyDrive/Amazon Review/Women Dresses Reviews Dataset .csv")

df.head()

df.info()

df.describe()

# Commented out IPython magic to ensure Python compatibility.
import missingno as msno
# %matplotlib inline
msno.matrix(df.sample(250))

corr=df.corr()
plt.figure(figsize=(14,10))
sns.heatmap(corr, annot=True, cmap='YlGnBu');

float_features = [f for f in df.columns if df[f].dtype == 'age']

# Training histograms
fig, axs = plt.subplots(4, 4, figsize=(16, 16))
for f, ax in zip(float_features, axs.ravel()):
    ax.hist(df[f], density=True, bins=100)
    ax.set_title(f'Train {f}, std={df[f].std():.1f}')
plt.suptitle('Histograms of the float features', y=0.93, fontsize=20)
plt.show()